import '../styles/globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const borderColor = 'border border-red-500'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${montserrat.className} bg-zinc-900 text-zinc-200`}>
      <div className={`container px-1 ${borderColor}`}>
        {children}
      </div>
      </body>
    </html>
  )
}
